#!/bin/sh

# Set decoration geometry
berryc border_width 0
berryc inner_border_width 0
berryc title_height 30
berryc top_gap 0

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "DejaVuSans"

wal -i "/home/aidan/Downloads/ccu.jpg"

sxhkd -c "/home/aidan/.config/berry/sxhkdrc"

sh "/home/aidan/.cache/wal/berrycolor"
